---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[docker-compose::default]
    attributes:
